seo:
  title: Productos - Mimu's Estilistas
  description: Descubre nuestra selección de productos profesionales de peluquería. Champús, tratamientos, styling y más para cuidar tu cabello en casa
title: Productos Profesionales
description: Llévate a casa los mejores productos para mantener tu cabello perfecto entre visita y visita. Trabajamos con las mejores marcas del mercado.
links:
  - label: "Ver servicios"
    to: "/servicios"
    color: "neutral"
  - label: 'Reserva tu cita'
    to: '/contacto'
    color: 'primary'
