title: Diseñando Interfaces, Construyendo Experiencias.
description: He trabajado en una variedad de productos, enfocándome en crear experiencias digitales intuitivas donde el diseño reflexivo se encuentra con código limpio. Aquí hay algunos destacados de los que estoy orgullosa, mostrando mi proceso desde el concepto hasta la ejecución.
links:
  - label: "Hablemos"
    color: "neutral"
  - label: 'Envíame un email'
